<!-- s: terms -->
        <div class="box-terms">
        		<h1 class="terms">TERMS & CONDITIONS</h1>
                
                <ol>
                		<li>
                            <h2>DESCRIPTION OF PRODUCTS, SERVICES AND ACCEPTANCE OF TERMS OF USE</h2>
                            <p><u>WWW.LIPUTAN6.COM</u> the property of, edited, maintained, owned and operated by <u>PT KREATIF MEDIA KARYA</u> ("Liputan6","KMK" "We," or "Us") provides an online video service offering a selection of live streaming, recorded highlights matches and other content ("Content"). </p>
                            <p>The Products we have provided/included in this site:</p>
                            <ul>
                            	<li>The <u>liputan6.com</u>'s website;</li>
                                <li>The <u>kickoff.liputan6.com</u> sub site; </li>
                                <li>Other websites where users or website operators are permitted to embed the Video Player.</li>
                            </ul>
                            
                            <p>Liputan6.com's Contents and Services include: </p>
                            <ul>
                            	<li>Live Streaming Package</li>
                                <li>Catch-up Match Package (VOD)</li>
                                <li>Magazine Highlights</li>
                                <li>Matches Highlights</li>
                            </ul>
                            <p><strong>Live Streaming Online</strong>. This Service section sets out the terms and conditions of our Live Streaming Online service, which allows you to stream Liputan6.com Contents and Service and other Content to your PC, laptop, mobile phone or other authorized device capable of receiving it (a "Device"). </p>
                            <p>When we use the word Device we include any service, guide, portal or gateway integrated with that Device. Where use of a Device may requires you to download any software which We provide to you.</p>
                            <p>Live Streaming Online service may not contain all the same features you will find on other impressions. The quality of the display of Live Streaming may vary from Device to Device, and may be affected by a variety of factors, such as the bandwidth available through and/or speed of your internet connection. </p>
                            <p>We may withdraw Live Streaming functionality entirely from our service or from any package or category of users. We may also limit, terminate, charge for or otherwise modify your use of the Live Streaming Online service at any time without notice; </p>
                            <p>However, we will give you notice before we institute any additional charges for the Live Streaming Online Service or any part of it. You acknowledge that due to requirements or requests from Content providers, or due to technical limitations, or for any reason in our sole and absolute discretion, and without prior notice to you, some or all Matches may not be viewed, or may cease being viewable, on our Live Streaming service at all or on some or all Devices. </p>
                            <p><strong>Ways to stream</strong>. You can stream and watch matches on the Live Streaming Online service in 3 (Three) ways: </p>
                            <ul>
                            	<li>Daily; or </li>
                                <li>Weekly; or </li>
                                <li>Monthly.</li>
                            </ul>
                            <p>Contents may not be able to be streamed and watched in all of these ways or on some or all Devices. This will be clear on the Website or Device, as applicable. </p>
                            <p><strong>Subscription</strong>. If you are an active member of our Live Streaming Online Service and your current Streaming Service package allows you to do so, you may stream on the Live Streaming service as part of your Streaming Service package. You can check whether this is the case in the "Profile" page on the Website. </p>
                            <p>Depending on your current Streaming Service package, we may limit the number of online viewing hours you are entitled to during a Subscription (your "Streaming Service Package,"). If your ability to stream and watch Matches on the Streaming Service Package, is subject to a Streaming Service Package, then the following paragraphs apply: </p>
                            <ul>
                            		<li>You will be allocated online viewing hours each Subscription Renewal Date in line with the Streaming Service Package, associated with your package for use during that Subscription;</li>
                            		<li>When you choose the Content to watch, the full run time of the Content will be deducted from your Streaming Service Package, (and you acknowledge that the run-time of a <strong>Content</strong> shall be determined by our records and systems and our decision as to a run time shall be final);</li>
                            		<li>If you do not have enough viewing hours left as part of your Streaming Service Package, to watch your chosen Content, you will not be able to watch it until the following Subscription Month if your Streaming Service Package, is big enough or, if it is not, unless you upgrade to a rental package which will either give you enough viewing hours per Subscription Month or will allow you unlimited online viewing on a subscription basis;</li>
                            		<li>Unused viewing hours will expire at the end of each Subscription Month and will not carry over to your next Subscription Month;</li>
                            		<li>If you change your Service Package during a Subscription Month to one with a different Streaming Service Package, your new Streaming Service Package, less any minutes already used by you that month will be allocated to your account immediately (please note this may result in a zero balance and you will have no more online viewing time until your next Subscription Month starts);</li>
                            		<li>If you bring your Subscription Renewal Date forward (i.e., make it earlier), your Streaming Service Package, will not be decreased; however, it will expire sooner (on your new Subscription Date); or if you if you push your Subscription Renewal Date back (i.e., make it later), you will not receive any additional minutes for that Subscription Month;</li>
                            		<li>Any additional minutes awarded to you by us for any reason will expire at the end of the Subscription Month in which they are awarded and will not carry over into the next Subscription Month;</li>
                            		<li>If you cancel your Monthly Subscription, any unused viewing hours will expire upon cancellation.</li>
                            </ul>
                            <p><strong>Equipment, Systems and Connectivity</strong>. Your ability to stream will depend on you having the necessary equipment, systems and connectivity. Before you buy subscribe, you must ensure that you have all necessary equipment, systems and connectivity to stream and watch the Matches properly. Minimum system requirements are specified in the Live Streaming Online section of the Website but even compliance with these does not guarantee that you will be able to stream Matches successfully. </p>
                            <p>You acknowledge that the availability of the Live Streaming Services may be affected by internet traffic congestion or by other network, ISP, electronic, computer or other communication problems or failures and that we are not responsible for the failure of any Matches to stream or to continue streaming due to any such congestion, problem or failure. </p>
                            <p><strong>Restrictions</strong>. You acknowledge all intellectual property and other rights in the <strong>Content</strong> that you stream and watch are owned by us or our licensors. To enforce those rights, we provide Services to you using technology that protects digital information and limits your ability to watch the <strong>Content</strong> in accordance with certain usage rules established by us and/or our licensors (whether in these Terms and Conditions and/or on the relevant pages of the Website and/or displayed on a Device). Accordingly, you undertake that: </p>
                            <ul>
                            		<li>You will stream and watch for personal, private use only (and not for any direct or indirect commercial purpose);</li>
                            		<li>You will not, and will not encourage or assist any other person to, copy, reproduce, lend, rent, broadcast, distribute or transmit any Services We provided;</li>
                            		<li>You will not, and will not encourage or assist any other person to, circumvent, modify, remove, reverse-engineer, decompile, disassemble, alter or otherwise tamper with any security, encryption or other rights management technology or software that is part of any Our Services or part of the means by which We provide to you; and</li>
                            </ul>
                            <p><strong>Termination and Enforcement</strong>. You acknowledge that, in addition to any rights that We or licensors have, any breach of these Terms and Conditions will entitle us to terminate your use of the service immediately and without notice. You specifically acknowledge our licensors have the right to directly enforce relevant provisions within these Terms and Conditions against you. We reserve the right to change, suspend, or cease your Subscription Services, or any part of it at any time and without notice to you. In particular, we reserve the right to remove any Matches from our catalogue or to cease your streaming and watching of any Matches on the Website or any Device if necessary to comply with our obligations to our licensors. You agree that, except for a reasonable refund in respect of any Matches you have bought to watch on a transactional basis, we will not be liable to you if we exercise those rights, even if your streaming is affected by the change, suspension or cessation.</p>
                            <p><strong>Payments</strong>. For your confines of using Our Product and Services, we provide the payment system, by using:</p>
                            <ul>
                            	<li><strong>Doku</strong>. One of the pioneers in Indonesian electronic payment industry specializing in Internet Payment Solutions Provider ("PSP") with local presence, DOKU is offering a one-stop/end to end Internet payment service, DOKU serves as a single gateway to facilitate both credit card acquirers (banks and credit card companies) and Internet merchants. (<a href="http://www.doku.com" target="_blank">www.doku.com</a>)</li>
                            	<li><strong>Visa Card</strong></li>
                            	<li><strong>Master Card</strong></li>
                            	<li><strong>Permata Virtual Account</strong></li>
                            	<li><strong>e-Pay BRI</strong></li>
                            </ul>                            
                        </li>
                        
                		<li>
                            <h2>CHANGES TO THE TERMS OF USE BY LIPUTAN6.COM</h2>
                            <p>We request that you bear in mind and take note upon accessing, browsing or utilizing the Website, the User accepts the terms and conditions indicated in this document and any additional terms and conditions indicated in any part of the Website, without limits or reservations.</p>
                            <p>We reserve the right to amend these terms and conditions, from time to time, with or without notice to you, to change these Terms and Conditions at our sole discretion. The Terms and Conditions applicable to your access to and use of this Website and your use and/or purchase of <strong>Liputan6.com</strong> Products and Services will be the version that is current and displayed on this Website as at each date you access this Website or use and/or purchase <strong>Liputan6.com</strong> Products and Services (as applicable). Your use of this Website or your use and/or purchase of <strong>Liputan6.com</strong> Products and Services after changes are made means that you agree to be bound by such changes. </p>
                        </li>
                        <li>
                        		<h2>ACCESS AND USE OF THE LIPUTAN6.COM SERVICES</h2>
                                <p>To become a Member of Liputan6.com or use or purchase any of the Liputan6.com Products and Services, as a minimum: </p>
                                <ul>
                                		<li>You must be at least 13 years of age. Persons under the age of 13 are not permitted to join Liputan6.com; </li>
                                		<li>You agree to must provide us with personal details (including your name, email address, postal address and valid payment details), that are true and current, and you agree to must update Us (through the "Profile" section of this Website) if at any time your personal details change by updating the relevant sections of the website.</li>
                                		<li>Liputan6.com is not intended to be used by children without involvement and approval of a parent or guardian. If you are under the age of 13, you are not permitted to register with Liputan6.com or provide your personal information to Liputan6.com. If you are at least 13 and under 18 years of age, you may register with Liputan6.com only if you have the consent of your parent or guardian.</li>
                                		<li>You may only access and view the Content personally and for a non-commercial purpose in compliance with these Terms. You may not either directly or through the use of any device, software, internet site, web-based service, or other means remove, alter, bypass, avoid, interfere with, or circumvent any copyright, trademark, or other proprietary notices marked on the Content or any digital rights management mechanism, device, or other content protection or access control measure associated with the Content including geo-filtering mechanisms. You may not either directly or through the use of any device, software, internet site, web-based service, or other means copy, download, stream capture, reproduce, duplicate, archive, distribute, upload, publish, modify, translate, broadcast, perform, display, sell, transmit or retransmit the Content unless expressly permitted by Liputan6.com in writing. You may not incorporate the Content into, or stream or retransmit the Content via, any hardware or software application or make it available via frames or in-line links unless expressly permitted by Liputan6.com in writing. Furthermore, you may not create, recreate, distribute or advertise an index of any significant portion of the Content unless authorized by Liputan6.com. You may not build a business utilizing the Content, whether or not for profit. The Content covered by these restrictions includes without limitation any text, graphics, layout, interface, logos, photographs, audio and video materials, and stills. In addition, you are strictly prohibited from creating derivative works or materials that otherwise are derived from or based on in any way the Content, including montages, mash-ups and similar videos, wallpaper, desktop themes, greeting cards, and merchandise, unless it is expressly permitted by Hulu in writing. This prohibition applies even if you intend to give away the derivative materials free of charge.</li>
                                </ul>
                        </li>
                        <li>
                        		<h2>ACCOUNTS AND REGISTRATION</h2>
                                <p>Every Product and Services features require a registration or the creation of an account with Liputan6.com. If at any time you choose to register or create an account with Us, the additional Terms and Conditions set forth below also will apply.</p>
                                <p>You are responsible for all use of your account, including use of your account by other members. By allowing others to access your account, you agree to be responsible for ensuring that they comply with these Terms of Use and you agree to be responsible for their activity using the Liputan6.com Services.</p>
                                <p>All registration information you submit must be accurate and updated. Please keep your password confidential. You will not have to reveal it to any party even to Liputan6.com representative. Because you are responsible for all use of your account, including unauthorized use by any third party please be very careful to guard the security of your password. </p>
                                <p>We reserve the right to immediately terminate or restrict your account or your use of the Liputan6.com Services or access to Content at any time, without notice or liability, if Liputan6.com determines in its sole discretion that you have breached these Terms of Use, violated any law, rule, or regulation, engaged in other inappropriate conduct, or for any other business reason. We also reserve the right to terminate your account or your use of the Liputan6.com Services or access to Content if such use places an undue burden on our networks or servers. </p>

                        </li>
                        <li>
                        		<h2>LINKED DESTINATIONS AND ADVERTISING</h2>
                                <p>We may provide links to other websites or services for you to access, including Facebook through the Liputan6.com Facebook Application, @liputan6dotcom Twitter, Liputan6dotcom YouTube's account, m.liputan6.com mobile application, and etc. You acknowledge that any access is at your sole discretion. We do not review or endorse any of those websites or services. If we provide links or pointers to the third party destinations or other websites.</p>
                                <p>You should not infer or assume that Liputan6.com operates, controls, or is otherwise connected with these other destinations or websites. When you click on a link within the Liputan6.com Services. In some cases, it may be less obvious than others that you have left Our site Services and reached another website or destination. Please be careful to read the terms of use and privacy policy of any other website or destination before you provide any confidential information or engage in any transactions. You should not rely on these Terms to govern your use of another website or destination.</p>
                                <p>We are not responsible in any way for: (a) the availability; (b) the privacy practices, (c) the content, advertising, products, goods or other materials or resources on or available from; or (d) the use to which others make of; these websites or services. We are also not responsible for any damage, loss or offence caused or alleged to be caused by, or in connection with, the use of or reliance on such websites or services.</p>
                                <p>By using the Liputan6.com Services, you acknowledge and agree that We are not going to responsible for the content or practices of any website or destination other than the Liputan6.com Site, even if it links to Our Site and even if the website or destination is operated by a company affiliated or otherwise connected with Liputan6.com.</p>
                                <p>You agree that We are not liable for any loss or claim that you may have against an advertiser and We will not giving you the responsibility for advertisements or any third party material Posted on any of the Properties, nor does it take any responsibility for the products or services provided by advertisers. Any dealings you have with advertisers found while using Our Services are between you and the advertiser. </p>
                        </li>
                        
                        <li>
                        		<h2>MATERIALS OF THIS WEBSITE </h2>
                                <p><strong>Trademarks</strong>. Liputan6.com, the Liputan6.com logo and all other Liputan6.com's products or services marks are trademarks of PT Kreatif Media Karya. All other trademarks, logos, images, product and company names displayed or referred to on the Website or any Device are the property of their respective owners. Nothing grants you any license or right to use, alter or remove such material.</p>
                                <p><strong>Copyright</strong>. All materials (including software and content whether downloaded or not) contained on the Website Products and Services are owned by Liputan6.com (or our affiliates and/or third party licensors (as applicable), unless indicated otherwise. You agree and acknowledge that the materials are valuable property and that other than any specific and limited license for use of content that you may purchase from the Website Products and Services to use such materials, you shall not acquire any ownership rights in or to such materials. The materials may not be used except as provided for in these Terms and Conditions, and any other relevant terms and conditions provided to you without our prior written permission. </p>
<P>You acknowledge and agree that certain content on the Website Products and  Services provided to you is the property of third party licensors and without prejudice to any and all other rights and remedies available, each such licensor has the right to directly enforce relevant provisions within these Terms and Conditions against you. </p>
                        </li>
                        
                        <li>
                        		<h2>DISCLAIMER OF WARRANTIES, LIMITATION OF LIABILITY AND INDEMNITY</h2>
                                <p>WHILE WE DO OUR BEST TO PROVIDE THE OPTIMAL PERFORMANCE OF THE LIPUTAN6.COM SERVICES, YOU AGREE THAT USE OF THE LIPUTAN6.COM SERVICES IS AT YOUR OWN RISK. THE LIPUTAN6.COM SERVICES, INCLUDING THE LIPUTAN6.COM SITE AND THE OTHER PROPERTIES, THE CONTENT, THE VIDEO PLAYER, USER MATERIAL, AND ANY OTHER MATERIALS CONTAINED ON OR PROVIDED THROUGH THE PROPERTIES, ARE PROVIDED "AS IS" AND, TO THE FULLEST EXTENT PERMITTED BY LAW, ARE PROVIDED WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITING THE FOREGOING, LIPUTAN6.COM DOES NOT MAKE ANY WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, TITLE, MERCHANTABILITY, COMPLETENESS, AVAILABILITY, SECURITY, COMPATIBILITY OR NONINFRINGEMENT; OR THAT THE LIPUTAN6.COM SERVICES WILL BE UNINTERRUPTED, FREE OF VIRUSES AND OTHER HARMFUL COMPONENTS, ACCURATE, ERROR FREE, OR RELIABLE.</p>
                                <p>IN NO EVENT SHALL LIPUTAN6.COM OR ITS AFFILIATES, SUCCESSORS, AND ASSIGNS, AND EACH OF THEIR RESPECTIVE INVESTORS, DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, AND SUPPLIERS (INCLUDING DISTRIBUTORS AND CONTENT LICENSORS) (COLLECTIVELY, THE "LIPUTAN6.COM PARTIES"), BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR OTHER DAMAGES, INCLUDING LOSS OF PROFITS, ARISING OUT OF OR IN ANY WAY RELATED TO THE USE OF THE LIPUTAN6.COM SERVICES (INCLUDING ANY INFORMATION, PRODUCTS, OR SERVICES ADVERTISED IN, OBTAINED ON, OR PROVIDED THROUGH THE PROPERTIES), WHETHER BASED IN CONTRACT, TORT, STRICT LIABILITY, OR OTHER THEORY, EVEN IF THE LIPUTAN6.COM PARTIES HAVE BEEN ADVISED OF THE POSSIBILITY OF DAMAGES. CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU. IN NO EVENT SHALL OUR TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES AND CAUSES OF ACTION WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE EXCEED THE AMOUNT PAID BY YOU TO US, IF ANY, FOR ACCESSING OR PARTICIPATING IN ANY ACTIVITY RELATED TO USE OF THE LIPUTAN6.COM SERVICE.</p>
                                <p>YOU AGREE TO DEFEND, INDEMNIFY, AND HOLD HARMLESS THE LIPUTAN6.COM PARTIES FROM AND AGAINST ANY AND ALL LIABILITIES, CLAIMS, DAMAGES, EXPENSES (INCLUDING REASONABLE ATTORNEYS' FEES AND COSTS), AND OTHER LOSSES ARISING OUT OF OR IN ANY WAY RELATED TO YOUR BREACH OR ALLEGED BREACH OF THESE TERMS OR YOUR USE OF THE LIPUTAN6.COM SERVICES (INCLUDING YOUR USE OF THE CONTENT). LIPUTAN6.COM RESERVES THE RIGHT, AT OUR OWN EXPENSE, TO EMPLOY SEPARATE COUNSEL AND ASSUMES THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER OTHERWISE SUBJECT TO INDEMNIFICATION BY YOU.</p>
                        </li>
                        <li>
                        		<h2>NOTICE AND CLAIMS PROCEDURE </h2>
                                <p>If you have any concerns about Content, User Material, or other material provided which appears on our site, including through a link, infringes your copyright, you should notify Liputan6.com of your infringement claim in accordance with the procedure set forth below.</p>
                                <p>We will process each notice of alleged infringement that Liputan6.com receives and take appropriate action in accordance with applicable laws. A notification of claimed should be emailed to Liputan6.Com's email at <a href="mailto:kickoff@liputan6.com">kickoff@liputan6.com</a> (subject line: "Claims"). </p>
                                <p>To be more effective, the notification letter must be in writing and contain the following information: (i) a physical signature; (ii) a description of the claim; (iii) a description of where the material that you claim is infringing is located on the Liputan6.com Services; (iv) how We can contact you, such as your address, telephone number, and email address; (v) a statement by you that the above information in your notice is accurate in the material. other than communication about notice and claims may not be answered.</p>
                        </li>
                        <li>
                        		<h2>APPLICABLE LAW</h2>
                                <p>The Website and liputan6.com's Products and Services are controlled by PT Kreatif Media Karya. The present Terms and Conditions of Use are governed and subject to Indonesian law, without reference to legal norms, and in the case of a dispute the User it will be submitted to the jurisdiction of the Republic of Indonesia courts. If any dispute arises out of these Terms and Conditions, Liputan6.com or any of its affiliates will attempt to settle it. To this end Liputan6.com shall use the reasonable endeavors to consult, negotiate in good faith, and attempt to reach a just and equitable settlement satisfactory to both parties.</p>
                                <p>To help us do that, you agree to begin any courts within one year after your claim arose; otherwise, your claim is waived. It is important that you understand that the court's decision will be binding and may be entered as a judgment in any court of competent jurisdiction. If the court rules against Us, in addition to accepting whatever responsibility is ordered by the court, we think it's fair that We reimburse your reasonable attorneys' fees and costs.</p>
                                <p>Since We always prefer to find ways to satisfy you as quickly and efficiently as possible, before initiating any legal proceeding, you agree to first discuss the matter informally with Us for at least 30 days. To do that, please send your full name and contact information, your concern and your proposed solution by mail to us at: SCTV Tower-Senayan City 14th Floor  Jl Asia Afrika Lot19 Jakarta 10270, Indonesia.- Attn: Legal Department.</p>
                                <p>If you're not sure what all of this means, of course please feel free to ask an attorney.</p>
                        </li>
                        <li>
                        		<h2>GENERAL INFORMATION</h2>
                                <p>Privacy. We collect personal information about you through and in connection with your use of the website and your use and/or purchase of Liputan6.com's Products and Services. All information that we collect about you is subject to our Privacy Policy, which forms part of these Terms and Conditions, and which may be accessed from our home page or by clicking here is deemed to be incorporated into these Terms and Conditions. </p>
                                <p>International Use. We are a company based in Indoneisa. Liputan6.com's goal is to bring you as much Content as is legally available. That said, We are limited by the rights that our content licensors grant to us. Using technologies to access the Content from territories where Liputan6.com does not have rights or does not offer services is prohibited. Our website is not accessible through any device from outside Indonesia territory.</p>
                                <p>No Waiver/Reliance. If you see other parties violating these Terms, we would appreciate it if you would let us know at  kickoff@liputan6.com (subject line: "T&C Violation"). If We fail to act in response to a violation of these Terms of Use, you should not assume that we do not object to the violation or even that we are aware of it. In addition, you may not construe a waiver of any provision of these Terms of Use with respect to any party as a waiver of that provision (or any other provision) with respect to either that party or any other party. If We delay exercising or fail to exercise or enforce any right available to us under these Terms and Conditions, such delay or failure does not constitute a waiver of that right or any other rights under these Terms and Conditions. </p>
                                <p>Integration, Amendment, and Severability. Please note that these Terms and Conditions, including Liputan6.com Privacy Policy which is incorporated in these Terms and any end user license agreement that might accompany Liputan6.com authorized applications, features and devices, constitute the entire legal agreement between you and Us and govern your use of the Liputan6.com Services (including your use of the Content) (but excludes any services, if any, that Liputan6.com may provide to you under a separate signed written agreement), and completely replaces any prior agreements between you and Liputan6.com in relation to the Liputan6.com Products and Services.</p>
                                <p>These Terms may not be amended or varied except in a writing signed by Liputan6.com. Although we understand that electronic or digital signatures are frequently viewed as the equivalent of traditional written signatures these days, for these purposes, a signature or "Signed" writing or written agreement may not include an electronic or digital signature. These Terms of Conditions operate to the fullest extent permissible by law. If any provision of these Terms is held to be unlawful, void, or unenforceable, you and we agree that the provision will be deemed severable from these Terms and will not affect the validity and enforceability of any remaining provisions.</p>
                                <p><strong>Force Majeure</strong>. For the purpose of these Terms and Conditions, "Force Majeure" means any cause beyond the control of one of the parties including, without limitation, act of God, war, insurrection, riot, civil disturbances, acts of terrorism, fire, explosion, flood, electricity black-out, network or server failure, theft of essential equipment, malicious damage, strike, lock out, weather, third party injunction, national defense requirements, actions taken by the police, acts or regulations of national or local governments. </p>
                                <p>We will not be liable to you for any lack of performance, or the unavailability or failure, of the Website or any of Liputan6.com's Products and Services, or for any failure or delay by us to comply with these Terms and Conditions, where such lack, unavailability or failure arises from any cause beyond our reasonable control. </p>
                        </li>
                        <li>
                        		<h2>PRIVACY POLICY</h2>
                                <p>Visiting the Website does not oblige the User to submit any information of a personal nature. However, the User is aware of and accepts that, in order to receive or access certain Services or Products, Subscription to the Website is necessary. This procedure involves the notification of certain personal data, and in said case the User recognizes that the subjection of any information of a personal nature remains subject to: </p>
                                <ul>
                                		<li>The User accepts that Liputan6.com registers the data file so that it can be used in the manner here indicated. This permission may be withdrawn only subject to request from the User. Notwithstanding the aforesaid, Liputan6.com may keep the data file until any actions that may arise from the relations between the parties have prescribed. The requested data is appropriate, relevant and not excessive in relation to the final means for which it shall be used, including any particular product or service required by the User from Liputan6.com or any of its affiliates as supplier of said Services or Products.</li>
                                		<li>The User expressly recognizes and accepts that Liputan6.com utilizes the collected information for the following purposes: the technical administration of the Website, the investigation and development for the purpose of obtaining and maintaining a high level of Service and for the occasional information of clients (related to the benefits and features of the membership), personalizing the Content seen by the User, to carry out the sending of requested information, products and/or services, and in order to contact the User in relation to special themes such as new products/services. </li>
                                		<li>The User expressly recognizes and accepts that Liputan6.com may send the data provided by the User to third companies for commercial and/or promotional purposes, either for Liputan6.com or for such third companies. Liputan6.com will require to the receiving parties of User's information to treat such information complying with the relevant applicable law, giving to the User any needed information in order for the User to be able to exercise its access, correction and cancellation rights if User should wish to exercise them.</li>
                                		<li>When proceeding with the collection of details, the voluntary or obligatory nature of such data will be clearly indicated. Declining to supply data considered obligatory will lead to the rejection of accessing the service for which they are required.</li>

                                </ul>
                                <p>Thank you for taking the time to read these Terms of Use. By understanding and agreeing to follow these Terms, the experience will be better for all users. Enjoy the Liputan6.com Services!</p>
                        </li>
                </ol>
                
                
        </div>
        <!-- e: terms -->
