<div id="header">
  <?php $this->load->view('v2/home/slide_campaign'); ?>
</div>

<div id="shared" class="fr"><?php $this->load->view('v2/social_buttons'); ?></div>

<div id="line" class="fl"></div>
<div class="cb"></div>
<div id="bar-black" class="fl"></div>
<div id="disclaimer-title">Syarat &amp; Ketentuan</div>

    <div class="box-terms">

<p class="western"><span><span style="font-size: x-large;"><strong>KETERANGAN PRODUK, JASA DAN PENERIMAAN KETENTUAN PENGGUNAAN </strong></span></span></p>
<p class="western" align="JUSTIFY"><a href="http://WWW.LIPUTAN6.COM/"><span style="color: #0000ff;"><span><span style="font-size: medium;"><span style="text-decoration: underline;">WWW.LIPUTAN6.COM</span></span></span></span></a><span><span style="font-size: medium;"> merupakan milik, diedit, dipelihara, dimiliki dan dioperasikan oleh ("Liputan6" atau "Kami"). Kami menyediakan layanan video online yang menawarkan pilihan </span></span><span><span style="font-size: medium;"><em>Live Streaming</em></span></span><span><span style="font-size: medium;">, rekaman Highlights Pertandingan dan konten lainnya ("konten"). <br />Produk-produk yang Kami sediakan/dalam website ini, antara lain: </span></span></p>
<ul>
<li>
<p class="western"><span><span style="font-size: medium;">Website liputan6.com; </span></span></p>
</li>
<li>
<p class="western"><span><span style="font-size: medium;">Sub Site bola.liputan6.com; kickoff.liputan6.com </span></span></p>
</li>
</ul>
<p class="western"><span><span style="font-size: medium;">Konten-konten dan Layanan-layanan &nbsp;Liputan6.com&nbsp; meliputi: </span></span></p>
<ul>
<li>
<p class="western"><span><span style="font-size: medium;">Paket Live Streaming</span></span></p>
</li>
<li>
<p class="western"><span><span style="font-size: medium;">Highlights Pertandingan </span></span></p>
</li>
<li>
<p class="western"><span><span style="font-size: medium;">Content News </span></span></p>
</li>
</ul>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><strong>Live Streaming Online. &nbsp;</strong></span></span><span><span style="font-size: medium;">Bagian Layanan &nbsp;ini menetapkan Syarat dan Ketentuan layanan Live Streaming Online, yang memungkinkan anda untuk melakukan </span></span><span><span style="font-size: medium;"><em>streaming</em></span></span><span><span style="font-size: medium;"> Konten milik Liputan6.com melalui PC, laptop, ponsel atau perangkat lain yang mampu dan mendukung untuk melakukan Live Streaming Online ("Perangkat"). Ketika Kami menggunakan kata Perangkat, termasuk, &nbsp;panduan, </span></span><span><span style="font-size: medium;"><em>Portal</em></span></span><span><span style="font-size: medium;"> atau </span></span><span><span style="font-size: medium;"><em>gateway</em></span></span><span><span style="font-size: medium;"> terintegrasi yang terhubung dengan Perangkat itu. Yang dimana mungkin &nbsp;meminta/mengharuskan anda untuk men-</span></span><span><span style="font-size: medium;"><em>download</em></span></span><span><span style="font-size: medium;"> perangkat lunak untuk mendukung anda dalam melakukan kegiatan Live Streaming Online; Kualitas pada &nbsp;Live Streaming Online yang Kami sediakan dapat bervariasi yang mungkin dapat dipengaruhi oleh berbagai faktor, seperti </span></span><span><span style="font-size: medium;"><em>bandwidth</em></span></span><span><span style="font-size: medium;"> yang tersedia melalui perangkat-perangkat dan/atau kecepatan koneksi internet anda;</span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Kami dapat menarik fungsi Live Streaming Online sepenuhnya dari layanan atau dari setiap paket atau kategori pengguna. Kami juga dapat membatasi, menghentikan, biaya untuk memodifikasi atau penggunaan layanan Live Streaming Online setiap saat tanpa pemberitahuan sebelumnya kepada anda/pengguna lainnya; </span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Namun, Kami akan memberikan pemberitahuan sebelumnya kepada anda jika ada biaya tambahan pada Layanan Live Streaming Online atau bagian dari itu. Anda mengakui bahwa karena persyaratan atau permintaan dari penyedia konten, atau karena keterbatasan teknis, atau untuk alasan apapun yang bersifat &nbsp;tunggal dan mutlak, dan tanpa pemberitahuan sebelumnya kepada anda, memungkinakan untuk tidak dapat mengakses beberapa Konten dalam &nbsp;Layanan Live Streaming Online kami dan anda mengakui apabila hal-hal tersebut terjadi diluar tanggung jawab Kami. </span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><strong>Cara untuk streaming</strong></span></span><span><span style="font-size: medium;">. Anda dapat melakukan streaming dan mengakses Konten pada layanan Live Streaming Online dengan sistem paket berbasis mingguan.</span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Beberapa Konten mungkin tidak dapat diakses dan digunakan dengan beberapa cara tersebut diatas atau dengan semua/beberapa Perangkat. Hal ini akan dijelaskan dalam website ini atau keterangan pada Perangkat anda. (Lihat Disclaimer)</span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><strong>Berlangganan</strong></span></span><span><span style="font-size: medium;">. Jika anda merupakan &nbsp;anggota/pelanggan aktif dari layanan Live &nbsp;Streaming Online Kami, anda dapat memeriksa mengenai status Paket layanan &nbsp;yang anda miliki pada "Profil" di website ini.</span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Bergantung pada status paket layanan live Streaming Online anda, Kami dapat membatasi jumlah Paket &nbsp;Berlangganan yang anda miliki, berdasarkan Paket Layanan Streaming ("Paket Layanan Live Streaming Online") anda. Dengan kondisi berlaku sebagai berikut: </span></span></p>
<ul>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Anda akan dapat melihat dan mengetahui paket yang anda miliki pada Profil akun anda, atau pada setiap saat anda memperpanjang/mendaftarkan/memperbaharui Paket Layanan Live Streaming Online, terkait dengan paket yang anda pilih untuk digunakan selama masa berlangganan;</span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Paket Layanan Live Streaming Online yang Anda miliki berbasis Mingguan berdasarkan </span></span><span><span style="font-size: medium;"><em>Match Day</em></span></span><span><span style="font-size: medium;"> pertandingan pada setiap liga. Untuk melihat/mengetahui pertandingan pada </span></span><span><span style="font-size: medium;"><em>Match Day</em></span></span><span><span style="font-size: medium;"> berikutnya maka anda harus memperpanjang/memperbaharui &nbsp;Paket berlangganan Anda; </span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Paket yang tidak anda gunakan bersifat kadaluarsa atau hangus pada jangka waktu yang ditentukan/tertentu sesuai dengan Paket Layanan Live Streaming Online yang sudah anda pilih, dan tidak dapat ditambahkan ke paket yang akan datang/lain;</span></span></p>
</li>
<li>
<p class="western"><span><span style="font-size: medium;">Anda tidak dapat menukar paket layanan yang dimiliki dengan paket lainnya.</span></span></p>
</li>
</ul>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><strong>Peralatan, sistem dan Konektivitas</strong></span></span><span><span style="font-size: medium;">. Kemampuan anda untuk melakukan streaming bergantung pada peralatan/perangkat yang diperlukan dan mendukung pada sistem dan konektivitas. Sebelum anda membeli/berlangganan Paket Layanan Live Streaming Online, anda harus memastikan bahwa anda memiliki semua peralatan/perangkat, sistem dan Konektivitas yang diperlukan dan mendukung untuk melakukan streaming. Penggunaan sistem minimum atau lebih sesuai dengan yang ditetntukan, tidak akan menjamin atas kelancaran pada Layanan Live Streaming Online dan Kami tidak bertanggung jawab atas hal tersebut. <br /><br />Anda mengakui bahwa Layanan Live Streaming Online akan dapat dipengaruhi oleh&nbsp; </span></span><span><span style="font-size: medium;"><em>internet</em></span></span><span><span style="font-size: medium;"><em>traffic</em></span></span><span><span style="font-size: medium;">, </span></span><span><span style="font-size: medium;"><em>ISP (Internet Service Provider)</em></span></span><span><span style="font-size: medium;">, masalah/kegagalan komunikasi dan hal-hal lain yang behubungan namun tidak terbatas, maka Kami tidak bertanggung jawab atas segala akibat dari hal-hal yang berhubungan dan dapat menyebabkan dan mempengaruhi kelancaran Layanan Live Streaming Online yang Kami sediakan, baik dari sisi internal maupun eksternal. Maka dengan ini anda mengakui bahwa , hal tersebut bukanlah merupakan tanggung jawab Kami sehingga&nbsp; Kami tidak bisa memberikan segala bentuk kompensasi dan atas hal itu pula anda tidak akan meminta ganti rugi dalam bentuk apapun dan dalam hal apapun. </span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><strong>Pembatasan</strong></span></span><span><span style="font-size: medium;">. Anda mengakui bahwa semua hak atas kekayaan intelektual dan hak lainnya dalam Konten pada Layanan Live Streaming Online dalam bentuk apapun, dimiliki oleh Kami atau Pemberi Lisensi. Untuk menegakkan hak-hak tersebut, Layanan yang Kami sediakan kepada anda menggunakan teknologi yang melindungi informasi digital dan membatasi kemampuan anda untuk mengakses &nbsp;Konten sesuai dengan aturan-aturan penggunaan yang ditetapkan oleh Kami dan/atau Pemberi Lisensi (baik yang ada dalam Syarat dan Ketentuan ini dan/atau ada pada halaman yang relevan di website ini dan/atau ditampilkan pada Perangkat yang anda gunakan). Dengan demikian, anda akan melakukan : </span></span></p>
<ul>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Anda akan </span></span><span><span style="font-size: medium;">streaming</span></span><span><span style="font-size: medium;"> dan mengakses untuk penggunaan pribadi saja (dan tidak untuk tujuan komersial baik secara langsung maupun tidak langsung dan secara sengaja maupun tidak sengaja); </span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Anda tidak akan, menyuruh, mempengaruhi atau membantu orang lain untuk, menyalin, memperbanyak, meminjamkan, menyewakan, menyiarkan, mendistribusikan, mentransmisikan atau hal lain yang sejenisnya dalam bentuk apapun dan tidak terbatas untuk Layanan yang Kami disediakan; </span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Anda tidak akan menyuruh, mempengaruhi atau membantu orang lain untuk, menghindari, memodifikasi, meretas, menghapus</span></span><span><span style="font-size: medium;"><em>, </em></span></span><span><span style="font-size: medium;">melakukan </span></span><span><span style="font-size: medium;"><em>reverse-engineer</em></span></span><span><span style="font-size: medium;">, menguraikan, membongkar, mengubah atau mengutak-atik keamanan apapun, enkripsi atau bentuk apapun yang tidak terbatas &nbsp;namun berhubungan dengan dan merupakan bagian dari setiap Layanan kami atau bagian dari sarana yang Kami berikan kepada anda.</span></span></p>
</li>
</ul>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><strong>Pemutusan dan Penegakan</strong></span></span><span><span style="font-size: medium;">. Anda mengakui bahwa, selain setiap hak yang Kami atau Pemberi Lisensi miliki, setiap pelanggaran terhadap Syarat dan Ketentuan ini akan memberikan kami kewenangan untuk dapat &nbsp;mengakhiri penggunaan Layanan Live Streaming Online dengan segera dan tanpa pemberitahuan seblumnya kepada anda. Anda secara khusus mengakui Pemberi Lisensi memiliki hak untuk secara langsung memberlakukan ketentuan yang relevan sesuai dengan Syarat dan Ketentuan ini terhadap anda. Kami berhak untuk mengubah, menangguhkan, atau menghentikan Layanan Live Streaming Online anda, atau bagian dari itu setiap saat dan tanpa pemberitahuan sebelumnya kepada anda. Secara khusus, kami berhak untuk menghapus Konten-konten yang ada dari katalog Kami atau untuk menghentikan </span></span><span><span style="font-size: medium;"><em>streaming</em></span></span><span><span style="font-size: medium;"> anda. Anda setuju bahwa, tidak ada pengembalian dana dalam bentuk apapun sehubungan dengan Konten Kami, maka Kami tidak akan bertanggung jawab kepada anda jika ada perubahan, penundaan atau penghentian atau hal yang tidak terbatas dan masih berhubungan dengan Layanan Live Streaming Online. </span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><strong>Sistem Pembayaran</strong></span></span><span><span style="font-size: medium;">. Untuk kenyamanan anda dalam menggunakan Produk dan Layanan yang Kami berikan, maka &nbsp;Kami menyediakan beberapa cara Sistem Pembayaran, antara lain:<br />&nbsp; </span></span></p>
<ul>
<li>
<p class="western"><span><span style="font-size: medium;">Doku;</span></span></p>
</li>
<li>
<p class="western"><span><span style="font-size: medium;">Visa Card; </span></span></p>
</li>
<li>
<p class="western"><span><span style="font-size: medium;">Master Card;</span></span></p>
</li>
<li>
<p class="western"><span><span style="font-size: medium;">Manual Transfer (Bank Central Asia, Bank Mandiri, Bank Negara Indonesia) </span></span></p>
</li>
</ul>
<p class="western">&nbsp;</p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Segala bentuk konfirmasi atas pembayaran akan anda terima, sesuai dengan sistem pembayaran yang anda lakukan. Untuk keterangan lebih lanjut perihal ini, anda dapat menghubungi Customer Service Kami. </span></span></p>
<p class="western"><br /><br /></p>
<p class="western"><span><span style="font-size: medium;"><strong>PERUBAHAN ATAS SYARAT DAN KETENTUAN OLEH LIPUTAN6.COM </strong></span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><br />Kami meminta agar anda mengingat dan memperhatikan saat mengakses atau menggunakan website Kami, anda mengakui bahwa anda&nbsp;menerima, telah membaca dan teleah mengerti isi dari seluruh Syarat dan Ketentuan yang ditunjukkan dalam setiap bagian dari website ini tanpa batas. Kami berhak untuk mengubah Syarat dan Ketentuan ini atas kebijakan kami dari waktu ke waktu, dengan atau tanpa pemberitahuan kepada anda. Syarat dan Ketentuan berlaku untuk penggunaan website ini dan pada pembelian dan/atau penggunaan Produk dan Layanan dari Liputan6.com. pada saat anda mulai mengakses, menggunakan, membeli Produk dan Layanan dari Liputan6.com maka secara lansung maupun tidak lansung&nbsp; anda sudah setuju dan terikat pada Syarat dan Ketentuan yang berlaku dan mengatur pada website ini.</span></span></p>
<p class="western"><span><span style="font-size: medium;"><strong>3. AKSES DAN PENGGUNAAN LAYANAN LIPUTAN6.COM </strong></span></span><span><span style="font-size: medium;"><br /><br />Untuk mendaftar, menggunakan atau membeli Produk dan Layanan dari Liputan6.com, maka anda :</span></span></p>
<ul>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Anda harus setidaknya berumur 13 tahun, jika anda dibawah usia 13 tahun anda dilarang untuk menjadi anggota, menggunakan atau membeli Produk dan Layanan dari Liputan6.com; </span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Liputan6.com tidak ditujukan untuk digunakan oleh anak-anak tanpa keterlibatan, bimbingan dan persetujuan dari orang tua, pengawas, pembimbing atau wali;</span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Anda setuju untuk memberikan Kami informasi pribadi anda secara benar dan terbaru (termasuk nama ,email, alamat lengkap, kode pos, rincian pembayaran yang valid, dan hal-hal lain yang kami butuhkan serta berhubungan dengan penggunaan Produk dan Layana dari Kami ), dan anda setuju untuk harus memberitahukan perkembangan menyangkut data diri anda kepada Kami (dengan merubah data diri anda melalui "Profil" pada website ini, sesuai dengan apa yang telah kami sediakan untuk anda);</span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Anda hanya dapat mengakses Konten secara pribadi dan untuk tujuan non-komersial sesuai dengan Syarat dan Ketentuan ini. Anda tidak diperbolehkan secara langsung maupun tidak langsung melalui penggunaan perangkat apapun baik, perangkat lunak, situs internet, layanan berbasis web, atau cara lain menghapus, mengubah, memotong, menghindari, mengganggu, atau menghindari hak cipta, merek dagang, atau hak kepemilikan lainnya atau mekanisme digital, </span></span><span><span style="font-size: medium;"><em>rights management</em></span></span><span><span style="font-size: medium;">, atau proteksi konten lainnya atau tindakan yang berhubungan dengan isi termasuk </span></span><span><span style="font-size: medium;"><em>geo-filtering mechanisms</em></span></span><span><span style="font-size: medium;">. </span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Anda juga tidak diperkenankan secara langsung maupun tidak langsung atau melalui penggunaan perangkat apapun, perangkat lunak, situs internet, layanan berbasis web, atau cara lain apapun untuk dan atau bertujuan menyalin, download, </span></span><span><span style="font-size: medium;"><em>steram capture</em></span></span><span><span style="font-size: medium;">, mereproduksi, menduplikasi arsip, mendistribusikan, meng-upload, mempublikasikan, memodifikasi, menerjemahkan, menyiarkan, menampilkan, menjual, mengirimkan atau memancarkan Konten kecuali secara tegas diizinkan oleh Liputan6.com secara tertulis;</span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Anda tidak dapat menggabungkan Materi-materi dan Konten tersebut ke dalam atau memancarkan melalui, perangkat keras atau aplikasi perangkat lunak atau membuatnya melalui </span></span><span><span style="font-size: medium;"><em>frame</em></span></span><span><span style="font-size: medium;"> atau </span></span><span><span style="font-size: medium;"><em>link in-line</em></span></span><span><span style="font-size: medium;"> kecuali secara tegas diizinkan oleh Liputan6.com secara tertulis. </span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Selain itu pula, anda tidak dapat membuat, menciptakan, mendistribusikan atau mengiklankan indeks dari setiap porsi yang signifikan dari Konten kecuali diizinkan oleh Liputan6.com. Anda tidak boleh memanfaatkan Konten untuk kepentingan usaha anda dalam bentuk apapun &nbsp;walaupun tidak bersifat komersil. </span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Konten dilindungi dan dibatasi termasuk tanpa terbatas oleh teks, grafis, tata letak, antarmuka, logo, foto, materi audio dan video, dan </span></span><span><span style="font-size: medium;"><em>stills</em></span></span><span><span style="font-size: medium;">. Selain itu, anda dilarang keras menciptakan karya turunan/tiruan atau materi lain yang berasal dari atau berdasarkan dengan cara apapun, termasuk </span></span><span><span style="font-size: medium;"><em>montages</em></span></span><span><span style="font-size: medium;"> , </span></span><span><span style="font-size: medium;"><em>mash-up</em></span></span><span><span style="font-size: medium;"> dan video yang sama, wallpaper, tema desktop kartu ucapan , dan barang dagangan, kecuali secara tegas diijinkan oleh Liputan6.com secara tertulis. </span></span></p>
</li>
</ul>
<p class="western">&nbsp;<span><span style="font-size: medium;"><strong>4.&nbsp; AKUN DAN &nbsp;PENDAFTARAN </strong></span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><br />Setiap Produk dan fitur Layanan Kami memerlukan pendaftaran atau pembuatan akun. Jika suatu saat anda memutuskan untuk mendaftar atau membuat akun pada website Kami, maka Syarat dan Ketentuan tambahan yang ditetapkan di bawah juga akan berlaku.<br /><br />Anda akan dan harus bertanggung jawab atas semua penggunaan akun milik anda, termasuk penggunaan akun milik anda yang diakses/digunakan oleh orang/pihak lain. Dengan membiarkan orang/pihak lain mengakses/menggunakan akun anda, maka anda setuju untuk bertanggung jawab atas aktivitas apapun yang dilakukan oleh pihak yang mengakses/menggunakan akun anda dalam segala bentuk Produk dan Layanan dari Liputan6.com.<br /><br />Anda diwajibkan untuk menjaga kerahasiaan password anda. Anda dilarang &nbsp;memberitahukan kepada pihak lain atau bahkan perwakilan dari Liputan6.com. Karena anda bertanggung jawab atas semua penggunaan akun anda, termasuk penggunaan yang tidak sah oleh pihak ketiga.<br /><br />Kami berhak untuk segera menghentikan atau membatasi atau me-non aktifkan &nbsp;akun anda untuk penggunaan/meng-akses Konten Layanan Liputan6.com jika anda telah melanggar Syarat dan Ketentuan ini, melanggar hukum, aturan, atau peraturan, terlibat dalam perilaku yang tidak pantas lainnya, atau karena alasan lainnya. </span></span></p>
<p class="western" align="JUSTIFY">&nbsp;</p>
<p class="western"><span><span style="font-size: medium;"><strong>5. TUJUAN TERKAIT DAN ADVERTISING </strong></span></span><span><span style="font-size: medium;"><br /></span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Kami mungkin menyediakan/menempatkan link ke website atau layanan lainnya yang dapat anda akses, termasuk aplikasi Facebook Liputan6.com, Twitter @liputan6dotcom, akun YouTube Liputan6dotcom, </span></span><span><span style="font-size: medium;"><em>mobile application</em></span></span><span><span style="font-size: medium;"> m.liputan6.com, dan lain-lain. Jika Kami memberikan link atau pointer ke website-website tertentu, maka anda harus mengakui dan menyadari bahwa Kami tidak meninjau/mendukung salah satu dari website atau jasa tersebut. ketika anda mengklik pada link dalam Layanan Liputan6.com anda tidak harus menyimpulkan atau berasumsi bahwa Liputan6.com beroperasi, meng-kontrol, atau terhubung dengan website-website lainnya tersebut.</span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Kami tidak bertanggung jawab dengan cara apapun untuk: (a)ketersediaan, (b)praktik privasi, (c)Konten, iklan, produk, barang atau mater-materi &nbsp;lain atau sumber daya yang tersedia dari, atau (d) penggunaan untuk yang lain membuat dari situs web atau layanan ini. Kami juga tidak bertanggung jawab atas kerusakan, kehilangan atau serangan yang disebabkan atau diduga disebabkan oleh atau sehubungan dengan penggunaan atau kepercayaan pada situs atau layanan tersebut. <br /><br />Dengan anda menggunakan Layanan Liputan6.com, anda mengakui dan setuju bahwa Kami tidak akan bertanggung jawab atas isi atau kegiatan salah satu website atau tujuan lain selain website Liputan6.com itu sendiri, bahkan jika ada link yang menuju website Kami dan dioperasikan oleh perusahaan yang berafiliasi atau berhubungan dengan Liputan6.com.<br /><br />Anda setuju bahwa Kami tidak bertanggung jawab atas segala kerugian atau klaim yang mungkin anda miliki terhadap pengiklan yang timbul akibat dari &nbsp;transaksi yang anda lakukan dengan pemasang iklan dengan atau pada saat menggunakan Layanan kami. </span></span></p>
<p class="western"><span><span style="font-size: medium;"><strong>6. MATERI DALAM WEBSITE </strong></span></span><span><span style="font-size: medium;"><br /></span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;"><strong>Merek Dagang.</strong></span></span><span><span style="font-size: medium;"> Logo dan semua Produk-produk dan Jasa dari Liputan6.com lainnya adalah merupakan merek dagang dari </span></span><span><span style="font-size: medium;"><span style="text-decoration: underline;">PT Kreatif Media Karya</span></span></span><span><span style="font-size: medium;">. Semua merek dagang lainnya, logo, gambar, produk dan nama perusahaan ditampilkan atau disebut pada website atau Perangkat apapun adalah milik masing-masing pemiliknya. Tidak ada yang memberi anda lisensi atau hak untuk menggunakan, mengubah atau menghapus materi tersebut. <br /><br /></span></span><span><span style="font-size: medium;"><strong>Hak Cipta.</strong></span></span><span><span style="font-size: medium;"> Semua materi (termasuk perangkat lunak dan konten hasil download atau tidak) yang terdapat/terkandung pada Produk dan Jasa yang dimiliki oleh website Liputan6.com (atau Afiliasinya dan/atau Pemberi Lisensi pihak ketiga (sebagaimana berlaku), Kecuali disebutkan lain. anda setuju dan mengakui, bahwa materi-materi tersebut memiliki nilai yang berharga, maka selain pemilik/pemegang lisensi khusus yang sah dan terbatas untuk penggunaan dari Produk dan Jasa website ini dilarang untuk untuk menggunakan materi tersebut, anda tidak akan mendapatkan hak kepemilikan atas materi-materi tersebut, kecuali sebagaimana diatur dalam Syarat dan Ketentuan ini, dan syarat-syarat lain yang relevan dan dengan izin tertulis resmi yang diberikan oleh Kami kepada anda. <br /><br />Anda mengakui dan setuju bahwa konten tertentu pada Produk website dan Layanan yang diberikan kepada anda adalah milik Pemberi Lisensi pihak ketiga dan tanpa mengurangi setiap hak dan upaya hukum yang tersedia, masing-masing lisensi tersebut berhak untuk secara langsung memberlakukan ketentuan yang relevan dalam Syarat dan Ketentuan ini untuk melawan anda. </span></span></p>
<p class="western">&nbsp;</p>
<p class="western"><span><span style="font-size: medium;"><strong>7 . PENOLAKAN JAMINAN, PEMBATASAN TANGGUNG JAWAB DAN GANTI RUGI</strong></span></span><span><span style="font-size: medium;"> <br /></span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">SAAT KAMI MELAKUKAN YANG TERBAIK UNTUK MEMBERIKAN KINERJA YANG OPTIMAL DARI LAYANAN LIPUTAN6.COM, ANDA SETUJU BAHWA PENGGUNAAN LAYANAN LIPUTAN6.COM MERUPAKAN RESIKO ANDA SENDIRI. LAYANAN LIPUTAN6.COM, TERMASUK WEBSITE LIPUTAN6.COM, KONTEN, </span></span><span><span style="font-size: medium;"><em>VIDEO PLAYER</em></span></span><span><span style="font-size: medium;">, DAN SEGALA MATERI LAIN YANG TERDAPAT PADA ATAU MELALUI WEBSITE LIPUTAN6.COM, "SEBAGAIMANA ADANYA" DAN, SEPENUHNYA SEJAUH DIIZINKAN OLEH HUKUM, YANG DIBERIKAN TANPA JAMINAN APAPUN, BAIK TERSURAT MAUPUN TERSIRAT. TANPA MEMBATASI HAL TERSEBUT, LIPUTAN6.COM TIDAK MEMBERIKAN JAMINAN KELAYAKAN UNTUK TUJUAN TERTENTU, HAK, KELENGKAPAN, KETERSEDIAAN, KEAMANAN, KOMPATIBILITAS ATAU BUKAN PELANGGARAN, ATAU BAHWA LAYANAN LIPUTAN6.COM AKAN TERGANGGU, BEBAS DARI VIRUS, KOMPONEN BERBAHAYA, AKURAT, BEBAS DARI KESALAHAN, ATAU DAPAT DIANDALKAN DAN HAL LAIN YANG TIDAK TERBATAS.<br /><br />DALAM KONDISI APAPUN LIPUTAN6.COM ATAU AFILIASINYA, PENERUS ,YANG DITUNJUK, DAN SETIAP INVESTOR, DIREKTUR, PETUGAS, KARYAWAN, AGEN, DAN PEMASOK (TERMASUK DISTRIBUTOR DAN LISENSI KONTEN) (SECARA KOLEKTIF, "PIHAK-PIHAK DARI LIPUTAN6.COM"), TIDAK BERTANGGUNG JAWAB SECARA LANGSUNG MAUPUN TIDAK LANGSUNG, TIDAK SENGAJA, KHUSUS , AKIBAT, ATAU LAINNYA, TERMASUK HILANGNYA KEUNTUNGAN YANG TIMBUL DARI ATAU BERKAITAN DENGAN PENGGUNAAN LAYANAN LIPUTAN6.COM (TERMASUK INFORMASI, PRODUK, ATAU LAYANAN YANG DIIKLANKAN, DIPEROLEH PADA, ATAU MELALUI KEPEMILIKAN), BAIK BERDASARKAN KONTRAK, KESALAHAN, KEWAJIBAN HUKUM, ATAU TEORI LAINNYA, BAHKAN JIKA PIHAK LIPUTAN6.COM TELAH DIBERITAHU TENTANG KEMUNGKINAN KERUSAKAN. </span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">ANDA SETUJU UNTUK MEMBELA, MENGGANTI KERUGIAN, DAN MEMBEBASKAN PIHAK LIPUTAN6.COM DARI DAN TERHADAP SETIAP DAN SEMUA KEWAJIBAN, KLAIM, KERUGIAN, BIAYA (TERMASUK BIAYA DAN BIAYA PENGACARA/KONSULTAN HUKUM), DAN KERUGIAN LAIN YANG TIMBUL DARI ATAU DALAM CARA APAPUN TERKAIT PELANGGARAN ATAU DUGAAN PELANGGARAN SYARAT DAN KETENTUAN INI ATAU PENGGUNAAN LAYANAN LIPUTAN6.COM (TERMASUK PENGGUNAAN KONTEN). LIPUTAN6.COM BERHAK, ATAS BEBAN KAMI SENDIRI, UNTUK MEMPEKERJAKAN PENASIHAT PROFESIONAL SECARA TERPISAH DAN DIKENAKAN/DIBEBANKANKEPADA ANDA </span></span></p>
<p class="western">&nbsp;</p>
<p class="western"><span><span style="font-size: medium;"><strong>8. PEMBERITAHUAN DAN PROSEDUR KLAIM </strong></span></span><span><span style="font-size: medium;"><br /><br />Jika anda mempunyai keluhan, saran atau pemberitahuan apapun menyangkut tentang Konten, Materi Pengguuna, atau materi lain yang muncul dalam website kami, termasuk melalui link, atau melanggar hak cipta seseorang, anda harus memberitahukan hal tersebut kepada pihak Liputan6.com sesuai dengan prosedur yang ditetapkan di bawah. <br /><br />Kami akan memproses setiap pemberitahuan dugaan pelanggaran yang Kami terima dan Kami akan mengambil tindakan yang tepat sesuai dengan hukum yang berlaku. Klaim pemberitahuan harus dikirim ke email Kami di </span></span><span><span style="font-size: medium;"><span style="text-decoration: underline;">kickoff@liputan6.com</span></span></span><span><span style="font-size: medium;"> (subject: "Klaim"). </span></span></p>
<p class="western">&nbsp;</p>
<p class="western"><span><span style="font-size: medium;"><strong>9. HUKUM YANG BERLAKU </strong></span></span><span><span style="font-size: medium;"><br /></span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Website, Produk dan Jasa milik &nbsp;Liputan6.com dikendalikan oleh PT Kreatif Media Karya. Syarat dan Ketentuan Penggunaan diatur dan tunduk pada hukum Negara Republik Indonesia, dalam yurisdiksi Pengadilan Republik Indonesia. Jika timbul sengketa dari Syarat dan Ketentuan ini, Liputan6.com atau afiliasinya akan mencoba untuk menyelesaikannya menggunakan upaya yang wajar untuk musyawarah, berkonsultasi, bernegosiasi dengan itikad baik, dan berusaha untuk mencapai penyelesaian yang adil dan musyawarah mufakat untuk memuaskan kedua belah pihak.<br /><br />Untuk membantu kami melakukan hal itu, anda setuju untuk memulai proses penyelesaian sengketa apapun dalam waktu kurang dari 30 (tiga puluh) hari setelah klaim anda muncul, jika anda tidak menindaklanjuti klaim tersebut, maka klaim yang anda ajukan akan dibatalkan. Penting untuk &nbsp;anda memahami bahwa keputusan pengadilan akan mengikat dan dapat dimasukkan sebagai keputusan dalam setiap pengadilan yang berwenang. </span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Karena Kami selalu berusaha untuk memberikan pelayanan yang terbaik, cepat dan seefisien mungkin kepada anda, sebelum memulai proses hukum apapun, anda setuju untuk membahas masalah secara informal dengan Kami selama minimal 14 (empat belas) hari. Untuk melakukan itu, anda dapat mengirimkan nama lengkap dan informasi kontak anda kepada Kami di: SCTV Tower-Senayan City 14th Floor Jl Asia Afrika Lot 19 Jakarta 10270, Indonesia - Attn:. Legal Department.<br /></span></span></p>
<p class="western"><span><span style="font-size: medium;"><strong>10 . INFORMASI UMUM </strong></span></span><span><span style="font-size: medium;"><br /><br /></span></span><span><span style="font-size: medium;"><strong>Privasi</strong></span></span><span><span style="font-size: medium;">. Kami mengumpulkan informasi pribadi tentang anda melalui dan sehubungan dengan penggunaan website dan penggunaan dan/atau pembelian Produk dan Jasa dari Liputan6.com. Semua informasi tentang diri anda berlaku dalam Kebijakan Privasi Kami, yang merupakan bagian dari Syarat dan Ketentuan ini, dan yang dapat diakses dari </span></span><span><span style="font-size: medium;"><em>homepage</em></span></span><span><span style="font-size: medium;"> kami. <br /><br /></span></span><span><span style="font-size: medium;"><strong>Penggunaan Internasional</strong></span></span><span><span style="font-size: medium;">. Kami adalah perusahaan yang berbasis di Indoneisa. Tujuan Liputan6.com adalah untuk memberikan anda Konten yang lengkap dan &nbsp;tersedia secara legal, yang dimana Kami diberikan hak terbatas oleh Pemberi Lisensi Konten. Oleh sebab itu, Website kami tidak dapat diakses melalui perangkat apapun dari luar wilayah Negara Republik Indonesia. <br /><br /></span></span><span><span style="font-size: medium;"><em><strong>Force Majeure</strong></em></span></span><span><span style="font-size: medium;">. Untuk tujuan dari Syarat dan Ketentuan ini, " Force Majeure" berarti sebab apapun di luar kendali salah satu pihak termasuk, tanpa batasan , tindakan Tuhan , perang , huru-hara, kerusuhan , gangguan sipil , tindakan terorisme , kebakaran, ledakan , banjir , listrik </span></span><span><span style="font-size: medium;"><em>black-out</em></span></span><span><span style="font-size: medium;"> , kegagalan jaringan atau server, pencurian peralatan penting , kerusakan berbahaya , pemogokan </span></span><span><span style="font-size: medium;"><em>, lock out</em></span></span><span><span style="font-size: medium;">, cuaca , permintaan dari pihak ketiga, persyaratan pertahanan nasional, tindakan Kepolisian, tindakan atau peraturan pemerintah pusat atau daerah. Maka Kami tidak akan bertanggung jawab kepada anda untuk setiap kurangnya kinerja, penundaan, tidak tersedianya atau kegagalan, dari website atau Produk dan Jasa dari Liputan6.com yang timbul dari sebab apapun di luar kendali Kami . </span></span></p>
<p class="western">&nbsp;</p>
<p class="western"><span><span style="font-size: medium;"><strong>11. KEBIJAKAN PRIVASI </strong></span></span><span><span style="font-size: medium;"><br /></span></span></p>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Mengunjungi website Kami &nbsp;tidak mewajibkan anda untuk menyerahkan informasi yang bersifat pribadi. Namun, pengguna menyadari dan menerima bahwa , dalam rangka untuk menerima atau mengakses/Berlangganan Layanan atau Produk Kami, diperlukan prosedur yang melibatkan/memerlukan anda untuk memberitahukan data pribadi tertentu milik anda, dan anda mengakui bahwa ketaatan informasi yang bersifat pribadi tetap tunduk pada:</span></span></p>
<ul>
<li>
<p class="western"><span><span style="font-size: medium;">Pengguna menerima dan mengakui bahwa Liputan6.com dapat menyimpan data sampai tindakan apapun yang mungkin timbul dari hubungan antara para pihak telah ditentukan. Data yang diminta harus sesuai, relevan dan tidak berlebihan dalam kaitannya dengan sarana final yang akan digunakan, termasuk produk atau jasa tertentu yang dibutuhkan oleh pengguna dari Liputan6.com atau afiliasinya;</span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Pengguna mengakui dan menerima Liputan6.com untuk dapat memanfaatkan/menggunakan informasi yang dikumpulkan untuk tujuan berikut: administrasi teknis website, penyelidikan dan pengembangan Produk dan Layanan tingkat tinggi dan untuk informasi klien yang situasional (terkait dengan manfaat dan fitur dari keanggotaan);</span></span></p>
</li>
<li>
<p class="western" align="JUSTIFY"><span><span style="font-size: medium;">Pengguna secara tegas mengakui dan menerima bahwa Liputan6.com dapat mengirimkan data yang diberikan oleh Pengguna kepada pihak ketiga untuk tujuan komersial dan/atau promosi, baik untuk Liputan6.com atau untuk pihak ketiga;<br /><br />Terima kasih telah membaca menyetujui dan mematuhi Syarat dan Ketentuan ini, selamat meikmati Layanan dari Liputan6.com ! </span></span></p>
</li>
</ul>
<p class="western">&nbsp;</p>

</div>
